import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header, Footer } from 'Components';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gulf Youth Bicycle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='bg-white'>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
